CREATE DATABASE IF NOT EXISTS wordpress_653;
CREATE DATABASE IF NOT EXISTS wordpress_593;
CREATE DATABASE IF NOT EXISTS wordpress_498;

CREATE USER 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON wordpress_653.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON wordpress_593.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON wordpress_498.* TO 'user'@'%';

FLUSH PRIVILEGES;
